---
title: "R Notebook"
output: html_notebook
---

# CASO PRÁCTICO 1

```{r}
# Crea un vector con la secuencia 1, 2, 3, 4, 5 de longitud 10.
v <- 1:10

# Crea un array de dos dimensiones, de 10 elementos cada una, con los 20 primeros números pares del 0 al 40.

aux.v <- c()

i <- 1

for (number in 0:40) {
  if(number %% 2 == 0) {
    aux.v[i] <- number
    
    i <- i + 1
  } else {
    next
  }
}

aux.v

# Crea una muestra de números aleatorios con repetición de longitud 10.
arr <- array(aux.v, c(10, 2))
arr

samp <- sample(1:100, 10, replace = T)
samp

# Crea un nuevo vector que sea el resultado de la suma fila a fila de cada dimensión del array.
arr.sums <- rowSums(arr)
arr.sums

# Finalmente, crea un dataframe con todas las estructuras de datos creadas anteriormente y muestra el resumen estadístico del dataframe.
df <- data.frame("columna_1"=v, "columna_2"=arr[, 1],
                 "columna_3"=arr[,2], "columna_4"=arr.sums)
```
# CASO PRÁCTICO
```{r}
vec.1 <- sample(1:100, 100, replace = T)
vec.2 <- sample(50:150, 100, replace = T)
vec.3 <- rep(c("2020", "2019", "2018", "2017", "2016"), 20)

# Crea una matriz de dos columnas con los vectores “vec.1” y “vec.2”.
mat <- matrix(c(vec.1, vec.2), nrow=100, ncol=2)
mat[1:10,]

# Crea un nuevo vector que sea la suma de las filas de la matriz al cuadrado
volume <- apply(mat, 1, sum)^2
volume[0:10]

"
Crea un dataframe con todos los vectores con las siguientes columnas:
  vec.1: Low.
  vec.2: High.
  Vector del apartado 2: Volume.
  vec.3: Year (tiene que ser una variable factor).
"

df <- data.frame("Low" = vec.1, "High" = vec.2, "Volumne" = volume, "Year" = as.factor(vec.3))
head(df)

# Muestra el resumen estadístico del dataframe.
summary(df)

# Muestra la estructura de variables del dataframe
str(df)

#  Asigna valor nulo (NA) a todos los valores de la columna Low por debajo de 20.
df[df$Low < 20, "Low"] <- NA
summary(df)

# Muestra el número de valores nulos de cada columna.
apply(is.na(df), 2, sum)

# Muestra la media de la columna Volume en función de cada factor de Year.
tapply(df$Volumne, df$Year, mean)

# Asigna a cada valor NaN, la media de la columna Low (pista, investigar en la función mean, como trabajar con nulos)
df$Low[which(is.na(df$Low))] <- mean(df$Low, na.rm = T)
summary(df)

# Obtén un sub-conjunto de los datos que sean todos los valores de 2020 y que tengan valor superior a 90 en la columna High.

year.values <- df[(df$High > 90 & df$Year == "2020"), ]
year.values

# Investiga sobre la función **`write.csv`**, crea un archivo csv con nombre "2020_Values"
write.csv(year.values, file = "2020_Values.csv", row.names = F)
```


